DFE-Digital/teach-in-further-education

spec/data/site/pages/page_experience_and_qalifications.yaml, spec/features/question_component_spec.rb
Unit tests for question component (On page: experience-and-qualifications.html)
Ensuring:
- correct number of elements are displayed
- class is correct
- submit button is displayed
=> Question component tests

spec/data/site/pages/page_find_an_fe_teaching_job.yaml, spec/features/find_fe_teaching_job_spec.rb
Unit tests for components found on the find a further education job page.
=> Find fe teaching job tests

.github/workflows/production.yml, manifest-prod.yml
Co-authored-by: hippostu <83215923+hippostu@users.noreply.github.com>
Co-authored-by: Colin Bull <colin.bull@digital.education.gov.uk>
=> Removing auth and bumping memory (#33)

.github/workflows/test.yml, nginx.conf
Testing the load balancing just in case we get an influx of users and need to limit the amount of users
=> add nginx.conf file for load balancing

spec/data/site/pages/page_with_help_and_advice.yaml, spec/features/help_and_advice_spec.rb
Tests for the components found on the /help-and-advice.html page. 
Assertions on elements, classes, links.
=> Help and advice tests

spec/features/homepage_spec.rb
Unit tests for components found on the homepage.
=> Homepage tests

spec/data/site/pages/page_with_404.yaml, spec/data/site/pages/page_with_500.yaml, spec/features/error_codes_spec.rb
Unit tests for 404 and 500 error pages.
=> Error codes tests

spec/data/site/pages/page_with_404.yaml, spec/data/site/pages/page_with_500.yaml, spec/features/error_codes_spec.rb
=> Regenerated error codes tests

spec/performance/Soak.js, spec/performance/soak_azure_pipeline.yaml
Added Pipeline yaml and Soak test script.
=> Added pipeline and test for Soak test

lib/markdown_helper.rb, source/_accordion.erb, source/_header.erb, source/_image.erb, source/_phase-banner.erb, source/_question.erb, source/layouts/layout.erb
Small changes for accessibility, Jean-Yves has checked.
=> Access changes

.github/workflows/e2eTest.yml
Experimenting with a new workflow.
=> Added e2eTest workflow

.github/workflows/e2eTest.yml, spec/e2e/e2eTests/E2e_test/Tests/User_journey.cs
=> Edited e2eTest.yml

DEV_GUIDE.md, spec/features/find_fe_teaching_job_spec.rb
Refactoring Unit tests, additions to DEV_GUIDE file.
=> Automation

spec/e2e/e2eTests/E2eTests.csproj
Finetuning nuget package to fix driver issue on github action.
=> Nuget package update to fix issue on github action

.github/workflows/e2eTest.yml, spec/e2e/RequestsTests/Request_tests/FindAnFeTeachingJob.Test.cs, spec/e2e/RequestsTests/Request_tests/GuideToFeTeaching.Test.cs, spec/e2e/RequestsTests/Request_tests/HelpAndAdvice.Test.cs, spec/e2e/RequestsTests/Request_tests/HomePage.Test.cs, spec/e2e/RequestsTests/Request_tests/TrainInYourOwnTime.Test.cs, spec/e2e/RequestsTests/Request_tests/TrainOnTheJob.Test.cs, spec/e2e/e2eTests/E2e_test/PageObjects/Homepage.cs, spec/e2e/e2eTests/E2e_test/Tests/User_journey_Dev.cs, spec/e2e/e2eTests/E2e_test/Tests/User_journey_PreProd.cs, spec/e2e/e2eTests/E2e_test/Tests/User_journey_Test.cs
Included Test and Pre-prod to E2E runs. I was toying with the idea of having them in the same class but decided to split them for now to accommodate with project timeline. In the future tests could be refactored so a unique test class is run several times depending on the environment.
Also expanded the Request tests to catch the environment specific issues related to contentful we've noticed lately. Those are not running on pipelines atm but run locally as and when, selecting the desired branch.
=> Refactoring

.github/workflows/request_handling_tests.yml
Adding the Request Handling Tests to a workflow, first trying it out separately before adding it to our existing workflows once it works as expected.
=> Starting again

.github/workflows/request_handling_tests.yml
Preparing future workflow so it's ready to be uncommented when further refactoring to the requests handling tests has been implemented.
=> Future workflow

spec/data/site/navs/header.yaml, spec/features/navigation_spec.rb
- Updated the nav test to reflect the current nav
- Broke out the header parts of the test to comprise their own test spec
=> Nav tests - Unit test refactoring

spec/features/header_spec.rb
- Added new spec for header test
- Started to use different method for asserting css after discovering that old method wasn't working
=> Header test - Unit test refactoring

spec/features/footer_spec.rb
- Refactored and expanded footer spec
=> refactored footer spec to reflect current content

source/_footer.erb, source/stylesheets/site.css.sass
Changed to navigation with mobile and desktop.
=> Navbar update

source/stylesheets/site.css.sass
V shaped arrow implemented for mobile navigation
=> Adding custom clip path to responsive menu button

spec/e2e/e2eTests/E2e_test/PageObjects/TrainInYourOwnTime.cs, spec/e2e/e2eTests/E2e_test/PageObjects/TrainOnTheJob.cs, spec/e2e/e2eTests/E2e_test/Tests/User_journey_Dev.cs, spec/e2e/e2eTests/E2e_test/Tests/User_journey_PreProd.cs, spec/e2e/e2eTests/E2e_test/Tests/User_journey_Test.cs
- Amended e2e tests to remove test steps around links that are no longer on the site
- Moved respective page objects that no longer exist
=> changes to e2e tests to reflect link changes on site

spec/e2e/e2eTests/E2eTests.csproj, spec/features/qualifications_question_spec.rb, spec/features/train_in_your_own_time_spec.rb
Quick fix to feature tests to fix change to heading selector on form.
=> Feature test fix 1

accessibility.txt, source/_accordion.erb, source/_advice.erb, source/_column_layout.erb, source/_cta.erb, source/_header.erb, source/_hero.erb, source/_phase-banner.erb, source/_question.erb, source/_story.erb, source/_table_of_contents.erb, source/templates/page.html.erb
Contains the following fixes:
- Added landmarks to all pages to contain all components
- Make changes to tables
- Adjusted attributes on radio buttons
- Various other a11y tweaks
=> A11y fixes 3

spec/e2e/e2eTests/E2e_test/PageObjects/AccessibilityAdvice.cs, spec/e2e/e2eTests/E2e_test/PageObjects/CookieBanner.cs, spec/e2e/e2eTests/E2e_test/PageObjects/CookiesPage.cs, spec/e2e/e2eTests/E2e_test/PageObjects/Footer.cs, spec/e2e/e2eTests/E2e_test/PageObjects/Homepage.cs, spec/e2e/e2eTests/E2e_test/PageObjects/Navigation.cs, spec/e2e/e2eTests/E2e_test/PageObjects/PrivacyPolicy.cs, spec/e2e/e2eTests/E2e_test/PageObjects/ResultsAlevels.cs, spec/e2e/e2eTests/E2e_test/PageObjects/ResultsDegree.cs, spec/e2e/e2eTests/E2e_test/PageObjects/ResultsGcse.cs, spec/e2e/e2eTests/E2e_test/PageObjects/ResultsNoQualifications.cs, spec/e2e/e2eTests/E2e_test/PageObjects/TrainInYourOwnTime.cs, spec/e2e/e2eTests/E2e_test/PageObjects/WhatYouCouldTeach.cs, spec/e2e/e2eTests/E2e_test/PageObjects/WhereToStartInFe.cs, spec/e2e/e2eTests/E2e_test/Tests/User_journey_Dev.cs, spec/e2e/e2eTests/E2e_test/Tests/User_journey_PreProd.cs, spec/e2e/e2eTests/E2e_test/Tests/User_journey_Test.cs
- Reviewed currently e2e flows
- Changed page objects to reflect changes to the site
- Added new page object files for newly added pages
- Fixed non-asserting test commands
=> refactored existing e2e tests and added new pages

.github/workflows/development.yml, .github/workflows/e2eTest_master.yml, .github/workflows/e2eTest_preprod.yml, .github/workflows/e2eTest_test.yml, .github/workflows/pre_production.yml, .github/workflows/production.yml, .github/workflows/test.yml
- Added new e2e test workflows to be triggered when new PR is raised for all envs above development
- Changed the current deploy workflows to include e2e tests
=> e2e test actions update

spec/e2e/e2eTests/E2e_test/Tests/User_journey_Dev.cs, spec/e2e/e2eTests/E2e_test/Tests/User_journey_PreProd.cs, spec/e2e/e2eTests/E2e_test/Tests/User_journey_Test.cs
- Removed flakey assertion - external link causing issues due to multiple redirects.
=> E2e update

spec/e2e/e2eTests/E2e_test/PageObjects/TrainInYourOwnTime.cs
- Changed the student finance link following change requested by myself and completed by Huw
=> change to student finance link

spec/e2e/e2eTests/E2e_test/PageObjects/Navigation.cs, spec/e2e/e2eTests/E2e_test/Tests/User_journey_Dev.cs, spec/e2e/e2eTests/E2e_test/Tests/User_journey_PreProd.cs, spec/e2e/e2eTests/E2e_test/Tests/User_journey_Test.cs
- Changed the home page nav link to site heading link following content change
- Added a scroll command to fix a new test issue on the cookies page
- Rectified an issue with the environment commands to ensure they point to correct environments
=> changed nav commands and fixed cookies page issue

spec/e2e/e2eTests/E2e_test/PageObjects/CookieBanner.cs, spec/e2e/e2eTests/E2e_test/Tests/User_journey_Dev.cs, spec/e2e/e2eTests/E2e_test/Tests/User_journey_PreProd.cs, spec/e2e/e2eTests/E2e_test/Tests/User_journey_Test.cs
- Further fix to e2e tests following changes to the cookie banner location.
=> fix to e2e tests following cookie banner move

spec/e2e/e2eTests/E2e_test/PageObjects/CookieBanner.cs
- Changed the selector for hide message buttons on cookie confirmation banners.
=> changes to cookie banner test

spec/e2e/RequestsTests/RequestsTests.csproj, spec/e2e/e2eTests/E2eTests.csproj, spec/e2e/e2eTests/E2e_test/Tests/User_journey_Dev.cs, spec/e2e/e2eTests/E2e_test/Tests/User_journey_PreProd.cs, spec/e2e/e2eTests/E2e_test/Tests/User_journey_Test.cs
- Removed an assertion which was causing issues due to page load times
- Updated packages
=> updated packages and removed an assertion

spec/e2e/e2eTests/E2e_test/Tests/User_journey_Dev.cs, spec/e2e/e2eTests/E2e_test/Tests/User_journey_PreProd.cs, spec/e2e/e2eTests/E2e_test/Tests/User_journey_Test.cs
- Removed troublesome assertion
=> removed troublesome assertion

spec/e2e/e2eTests/E2e_test/PageObjects/SignUpToNewsletter.cs, spec/e2e/e2eTests/E2e_test/Tests/User_journey_Dev.cs, spec/e2e/e2eTests/E2e_test/Tests/User_journey_PreProd.cs, spec/e2e/e2eTests/E2e_test/Tests/User_journey_Test.cs
- Removed the cookie banner hide command - causing more issues than it was benefitting
- Added a scroll command to the homepage due to hide banner still being shown
- Added newsletter tests
=> test fixes and addition of newsletter test

spec/e2e/e2eTests/E2e_test/Tests/User_journey_Dev.cs, spec/e2e/e2eTests/E2e_test/Tests/User_journey_PreProd.cs, spec/e2e/e2eTests/E2e_test/Tests/User_journey_Test.cs
- Due to continued error in e2e tests, changed scroll to refresh
=> changed the scroll to refresh in tests

spec/e2e/e2eTests/E2e_test/Tests/User_journey_Dev.cs, spec/e2e/e2eTests/E2e_test/Tests/User_journey_PreProd.cs, spec/e2e/e2eTests/E2e_test/Tests/User_journey_Test.cs
- Added more commands to ensure that homepage is loaded
=> further changes to e2e tests

source/_cta.erb
- Changed the aria-label for cta landmark region
=> changed the landmark for cta button label

spec/data/site/navs/footer.yaml, spec/data/site/navs/header.yaml, spec/data/site/pages/home.yaml, spec/data/site/pages/page_find_a_job.yaml, spec/data/site/pages/page_sign_up_for_our_newsletter.yaml, spec/data/site/pages/page_train_in_your_own_time.yaml, spec/data/site/pages/page_train_on_the_job.yaml, spec/data/site/pages/page_what_you_could_teach.yaml, spec/data/site/pages/page_where_to_start.yaml, spec/data/site/pages/page_with_help_and_advice.yaml, spec/data/site/pages/page_wyct_with_accordion.yaml, spec/features/find_a_job_spec.rb, spec/features/footer_spec.rb, spec/features/help_and_advice_spec.rb, spec/features/hero_spec.rb, spec/features/homepage_spec.rb, spec/features/homepage_stories_spec.rb, spec/features/homepage_summary_spec.rb, spec/features/navigation_spec.rb, spec/features/newsletter_sign_up_spec.rb, spec/features/train_in_your_own_time_spec.rb, spec/features/train_on_the_job_spec.rb, spec/features/what_you_could_teach_spec.rb, spec/features/where_to_start_in_fe_spec.rb, spec/features/wyct_accordion_spec.rb
- Updated test yaml files
- Updated the test spec files
=> changes to test specs and yaml files

spec/e2e/e2eTests/E2e_test/PageObjects/FindAnFeTeachingJob.cs, spec/e2e/e2eTests/E2e_test/PageObjects/WhereToStartInFe.cs, spec/e2e/e2eTests/E2e_test/Tests/User_journey_Dev.cs, spec/e2e/e2eTests/E2e_test/Tests/User_journey_PreProd.cs, spec/e2e/e2eTests/E2e_test/Tests/User_journey_Test.cs
- Changed the where to start and find a job links to reflect site changes
=> E2e update 2

spec/e2e/e2eTests/E2e_test/PageObjects/TrainOnTheJob.cs
- Updated the links on the 'train on the job' page
=> changes to links on e2e tests

spec/e2e/e2eTests/E2e_test/PageObjects/TrainOnTheJob.cs, spec/e2e/e2eTests/E2e_test/Tests/User_journey_Dev.cs, spec/e2e/e2eTests/E2e_test/Tests/User_journey_PreProd.cs, spec/e2e/e2eTests/E2e_test/Tests/User_journey_Test.cs
- Removed the depreciated links
- Added new the new links
=> changed tests to reflect new content

spec/e2e/e2eTests/E2e_test/Tests/User_journey_Dev.cs
- Added scroll command to attempt to fix college jobs issue
=> hotfix for college jobs link issues

.github/workflows/production.yml, spec/e2e/e2eTests/E2e_test/PageObjects/Navigation.cs, spec/e2e/e2eTests/E2e_test/Tests/User_journey_PreProd.cs, spec/e2e/e2eTests/E2e_test/Tests/User_journey_Prod.cs, spec/e2e/e2eTests/E2e_test/Tests/User_journey_Test.cs
- Added a new e2e test for production
- Updated the navigation page objects to include production url commands
- Edited the production workflow to include test job to run in parallel with monitor job
- Updated all the e2e tests to match development
=> E2e prod test

source/stylesheets/site.css.sass
- Swapped `scroll-padding-top` for `scroll-margin-top` in order to fix scroll position issues.
=> reinstated fix for scroll position

spec/e2e/e2eTests/E2e_test/Tests/User_journey_Dev.cs, spec/e2e/e2eTests/E2e_test/Tests/User_journey_PreProd.cs, spec/e2e/e2eTests/E2e_test/Tests/User_journey_Prod.cs, spec/e2e/e2eTests/E2e_test/Tests/User_journey_Test.cs
- Changed a link on find a job page
=> changed link following content change

spec/e2e/e2eTests/E2e_test/Tests/User_journey_Dev.cs
- Added scroll command to attempt to prevent missing element error
=> added scroll to prevent error

js/consent.js, source/layouts/layout.erb, spec/e2e/e2eTests/E2e_test/Tests/User_journey_PreProd.cs, spec/e2e/e2eTests/E2e_test/Tests/User_journey_Prod.cs, spec/e2e/e2eTests/E2e_test/Tests/User_journey_Test.cs
- Reverted the GA fix from last week as this was causing issues with the cookie confirmation banner
- Updated environment e2e tests with scrolls
=> reverted GA fix and added in scroll to e2e tests

spec/e2e/e2eTests/E2e_test/PageObjects/HelpAndAdvice.cs, spec/e2e/e2eTests/E2e_test/Tests/User_journey_Dev.cs, spec/e2e/e2eTests/E2e_test/Tests/User_journey_PreProd.cs, spec/e2e/e2eTests/E2e_test/Tests/User_journey_Prod.cs, spec/e2e/e2eTests/E2e_test/Tests/User_journey_Test.cs
- Added phone numbers to tests
- Added tests to check charges link
- Replaced email addresses where no longer shown
=> E2e phone fixes

spec/e2e/e2eTests/E2e_test/Tests/User_journey_Prod.cs
- Added missing init to the prod e2e test file
=> added init to prod test
